#!/bin/sh
# 충돌 없는 `git merge` 는 pre-commit 이 아니라 이 훅을 호출한다.
# 병합 커밋도 pre-commit 과 동일하게 검사한다. (DL-0028)
# 이 시점에는 MERGE_HEAD 가 아직 없으므로 위치 인자로 알린다(환경변수는 위조 가능하므로 사용하지 않음).
# git merge 는 인덱스에 별도 스테이징이 있으면 병합을 거부하므로, 여기서 스테이징된 내용은 전부 병합 결과다.
exec sh "$(dirname "$0")/pre-commit" --from-pre-merge-commit
